### ISSUE TITLE
any type

### ISSUE THREAD

**Issue by serfezea-navitasoft** [SzoDavid/tr-demo-web#2]
https://github.com/SzoDavid/tr-demo-web/blob/c7ac6cd232e7ad531062ce3e397c017553a2bc37/src/app/app.component.ts#L38

sose használjunk `any` típust, tudjuk hogy `boolean`-t emittál a child.
a változó neve legyen beszédesebb, pl `shouldClose`
az if-et is szépítheted, nem kell a boolean értéket csekkolni:

```
if (shouldClose) {
```

**Comment by SzoDavid** [comment]
Na ezt visszanézve tényleg vicces. Ezt még amikor tanultuk az angulart, akkor másoltam ki a tananyagból és most is, ha már működik, akkor ne piszkáljuk alapon újra felhasználtam
