### ISSUE TITLE
redirect to not found page?

### ISSUE THREAD

**Issue by serfezea-navitasoft** [SzoDavid/tr-demo-web#3]
https://github.com/SzoDavid/tr-demo-web/blob/c7ac6cd232e7ad531062ce3e397c017553a2bc37/src/app/app-routing.module.ts#L46

ha random path-et írunk be, nem a `not-found` path-re kellene redirect-elni?

**Comment by SzoDavid** [comment]
Alapból nem volt not-found, később adtam hozzá, amikor id-k kerültek az útvonalakba és az volt az elképzelés, hogy ez arra vonatkozna csak, amikor az id-k invalidak
